name: todo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.2.1
  table_calendar: ^3.2.0
  sqflite: ^2.0.0+4
  path: ^1.8.0
  fl_chart: ^0.70.2
  audioplayers: ^5.2.1
  shared_preferences: ^2.0.15
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/announcement-sound-effect-254037.mp3

