// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Sg6NoChjJ9c_Y67hKziUjvqO0mFUgX0',
    appId: '1:744582234805:web:6905da382e93efc2cf74fc',
    messagingSenderId: '744582234805',
    projectId: 'todolistapp-cfdd9',
    authDomain: 'todolistapp-cfdd9.firebaseapp.com',
    storageBucket: 'todolistapp-cfdd9.firebasestorage.app',
    measurementId: 'G-634JBHW7J2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1hSJNHsOdXAZKiPpo0lJN9tfY_eTJPEM',
    appId: '1:744582234805:android:20badc751007e27ccf74fc',
    messagingSenderId: '744582234805',
    projectId: 'todolistapp-cfdd9',
    storageBucket: 'todolistapp-cfdd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk1xyY5To9M78CdvZO0xO45n8gihri5_o',
    appId: '1:744582234805:ios:e65bdb0767d43cc0cf74fc',
    messagingSenderId: '744582234805',
    projectId: 'todolistapp-cfdd9',
    storageBucket: 'todolistapp-cfdd9.firebasestorage.app',
    iosClientId: '744582234805-m8f58up62jbd6oa7oumktds5c6ika1jt.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk1xyY5To9M78CdvZO0xO45n8gihri5_o',
    appId: '1:744582234805:ios:e65bdb0767d43cc0cf74fc',
    messagingSenderId: '744582234805',
    projectId: 'todolistapp-cfdd9',
    storageBucket: 'todolistapp-cfdd9.firebasestorage.app',
    iosClientId: '744582234805-m8f58up62jbd6oa7oumktds5c6ika1jt.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
